services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - redis-master
    networks:
      - nginx-php-redis
  php-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php-redis

# Редис мастер для записи
  redis-master:
    image: bitnami/redis:latest
    container_name: redis-master
    volumes:
      - ./redis-data-master:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.redis-master == true
    ports:
      - "6379:6379"
    networks:
      - nginx-php-redis
      - app-tier

  # Редис слейв
  redis-slave:
    image: bitnami/redis:latest
    command: ["redis-server", "--slaveof", "redis-master", "6379", "--protected-mode", "no"]
    container_name: redis-slave
    volumes:
      - ./redis-data-slave:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
    ports:
      - "6479:6489"
    networks:
      - nginx-php-redis
      - app-tier
    depends_on:
      - redis-master

networks:
  nginx-php-redis:
    external: true
  app-tier:
    driver: bridge