services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - redis-master
    networks:
      - nginx-php-redis
  php-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php-redis

  redis-master:
    image: redis:latest
    container_name: redis-master
    volumes:
      - ./redis-data-master:/data
    ports:
      - "6379:6379"
    networks:
      - nginx-php-redis
      - app-tier

  redis-slave:
    image: redis:latest
    container_name: redis-slave
    volumes:
      - ./redis-data-slave:/data
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - nginx-php-redis
      - app-tier

networks:
  nginx-php-redis:
  app-tier:
    driver: bridge