controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_update_statistics:
    path: /update/{country}
    controller: App\Controller\StatisticsController::update

app_get_statistics:
    path: /statistics
    controller: App\Controller\StatisticsController::get